
[env]
TERM = "xterm-256color"

[cursor]
unfocused_hollow = true

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font Mono"

[font.bold]
style = 'normal'

[scrolling]
history = 4000

[shell]
program = "/bin/zsh"
args = ["-l","-c","tmux attach || tmux"]

[window]
decorations = 'Buttonless'
