
[env]
TERM = "xterm-256color"

[cursor]
unfocused_hollow = true

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font Mono"


[scrolling]
history = 4000

[shell]
program = "/bin/zsh"
args = ["-l","-c","tmux attach || tmux"]

